// Staging prompts for each style
// Default prompt and specialized prompts for each style

export const DEFAULT_STAGING_PROMPT = (
  roomType: string,
  stagingStyle: string
) =>
  `Virtually stage this ${roomType} in ${stagingStyle} style. Add furniture, lighting, and decor. Do NOT change the architecture (doors, windows, walls, ceiling, layout, or any fixed features), do NOT change light holder positions, and do NOT change the lighting coming from outside. Do NOT remove, hide, or alter any original paintings, wall art, or decorative items unless the user prompt or remove furniture option explicitly requests it. If the room is already furnished, do NOT change the full layout—just improve or enhance the existing furnishings and decor. Keep all original decor and artwork unless instructed otherwise. Make it look inviting and professional for a real estate listing.`;

export const STAGING_STYLE_PROMPTS: Record<string, (roomType: string) => string> = {
  modern: (roomType) =>
    `Virtually stage this ${roomType} in modern style. Use clean lines, neutral colors, and minimal clutter. Do NOT change the architecture (doors, windows, walls, ceiling, layout, or any fixed features), do NOT change light holder positions, and do NOT change the lighting coming from outside. Do NOT remove, hide, or alter any original paintings, wall art, or decorative items unless the user prompt or remove furniture option explicitly requests it. If the room is already furnished, do NOT change the full layout—just improve or enhance the existing furnishings and decor. Keep all original decor and artwork unless instructed otherwise. Add contemporary furniture and subtle decor for a sleek, inviting look.`,
  contemporary: (roomType) =>
    `Virtually stage this ${roomType} in contemporary style. Use current trends, open spaces, and a mix of textures. Do NOT change the architecture (doors, windows, walls, ceiling, layout, or any fixed features), do NOT change light holder positions, and do NOT change the lighting coming from outside. Do NOT remove, hide, or alter any original paintings, wall art, or decorative items unless the user prompt or remove furniture option explicitly requests it. If the room is already furnished, do NOT change the full layout—just improve or enhance the existing furnishings and decor. Keep all original decor and artwork unless instructed otherwise. Add stylish furniture and modern art.`,
  minimalist: (roomType) =>
    `Virtually stage this ${roomType} in minimalist style. Use simple, functional furniture, neutral palette, and minimal decor. Do NOT change the architecture (doors, windows, walls, ceiling, layout, or any fixed features), do NOT change light holder positions, and do NOT change the lighting coming from outside. Do NOT remove, hide, or alter any original paintings, wall art, or decorative items unless the user prompt or remove furniture option explicitly requests it. If the room is already furnished, do NOT change the full layout—just improve or enhance the existing furnishings and decor. Keep all original decor and artwork unless instructed otherwise. Emphasize open space and calmness.`,
  scandinavian: (roomType) =>
    `Virtually stage this ${roomType} in Scandinavian style. Use light woods, white walls, cozy textiles, and functional furniture. Do NOT change the architecture (doors, windows, walls, ceiling, layout, or any fixed features), do NOT change light holder positions, and do NOT change the lighting coming from outside. Do NOT remove, hide, or alter any original paintings, wall art, or decorative items unless the user prompt or remove furniture option explicitly requests it. If the room is already furnished, do NOT change the full layout—just improve or enhance the existing furnishings and decor. Keep all original decor and artwork unless instructed otherwise. Add warmth and simplicity.`,
  industrial: (roomType) =>
    `Virtually stage this ${roomType} in industrial style. Use exposed materials, metal fixtures, and urban decor. Do NOT change the architecture (doors, windows, walls, ceiling, layout, or any fixed features), do NOT change light holder positions, and do NOT change the lighting coming from outside. Do NOT remove, hide, or alter any original paintings, wall art, or decorative items unless the user prompt or remove furniture option explicitly requests it. If the room is already furnished, do NOT change the full layout—just improve or enhance the existing furnishings and decor. Keep all original decor and artwork unless instructed otherwise. Add loft-inspired furniture and accents.`,
  traditional: (roomType) =>
    `Virtually stage this ${roomType} in traditional style. Use classic furniture, rich colors, and elegant decor. Do NOT change the architecture (doors, windows, walls, ceiling, layout, or any fixed features), do NOT change light holder positions, and do NOT change the lighting coming from outside. Do NOT remove, hide, or alter any original paintings, wall art, or decorative items unless the user prompt or remove furniture option explicitly requests it. If the room is already furnished, do NOT change the full layout—just improve or enhance the existing furnishings and decor. Keep all original decor and artwork unless instructed otherwise. Add timeless appeal and comfort.`,
  transitional: (roomType) =>
    `Virtually stage this ${roomType} in transitional style. Blend traditional and modern elements. Do NOT change the architecture (doors, windows, walls, ceiling, layout, or any fixed features), do NOT change light holder positions, and do NOT change the lighting coming from outside. Do NOT remove, hide, or alter any original paintings, wall art, or decorative items unless the user prompt or remove furniture option explicitly requests it. If the room is already furnished, do NOT change the full layout—just improve or enhance the existing furnishings and decor. Keep all original decor and artwork unless instructed otherwise. Use a balanced mix of classic and contemporary furniture.`,
  farmhouse: (roomType) =>
    `Virtually stage this ${roomType} in farmhouse style. Use rustic wood, cozy fabrics, and vintage accents. Do NOT change the architecture (doors, windows, walls, ceiling, layout, or any fixed features), do NOT change light holder positions, and do NOT change the lighting coming from outside. Do NOT remove, hide, or alter any original paintings, wall art, or decorative items unless the user prompt or remove furniture option explicitly requests it. If the room is already furnished, do NOT change the full layout—just improve or enhance the existing furnishings and decor. Keep all original decor and artwork unless instructed otherwise. Add warmth and charm.`,
  coastal: (roomType) =>
    `Virtually stage this ${roomType} in coastal style. Use light colors, natural textures, and breezy decor. Do NOT change the architecture (doors, windows, walls, ceiling, layout, or any fixed features), do NOT change light holder positions, and do NOT change the lighting coming from outside. Do NOT remove, hide, or alter any original paintings, wall art, or decorative items unless the user prompt or remove furniture option explicitly requests it. If the room is already furnished, do NOT change the full layout—just improve or enhance the existing furnishings and decor. Keep all original decor and artwork unless instructed otherwise. Add a relaxed, beach-inspired feel.`,
  bohemian: (roomType) =>
    `Virtually stage this ${roomType} in bohemian style. Use eclectic furniture, vibrant colors, and layered textiles. Do NOT change the architecture (doors, windows, walls, ceiling, layout, or any fixed features), do NOT change light holder positions, and do NOT change the lighting coming from outside. Do NOT remove, hide, or alter any original paintings, wall art, or decorative items unless the user prompt or remove furniture option explicitly requests it. If the room is already furnished, do NOT change the full layout—just improve or enhance the existing furnishings and decor. Keep all original decor and artwork unless instructed otherwise. Add artistic and free-spirited decor.`,
  "mid-century": (roomType) =>
    `Virtually stage this ${roomType} in mid-century style. Use retro furniture, bold patterns, and warm woods. Do NOT change the architecture (doors, windows, walls, ceiling, layout, or any fixed features), do NOT change light holder positions, and do NOT change the lighting coming from outside. Do NOT remove, hide, or alter any original paintings, wall art, or decorative items unless the user prompt or remove furniture option explicitly requests it. If the room is already furnished, do NOT change the full layout—just improve or enhance the existing furnishings and decor. Keep all original decor and artwork unless instructed otherwise. Add vintage flair and simplicity.`,
  luxury: (roomType) =>
    `Virtually stage this ${roomType} in luxury style. Use high-end furniture, elegant finishes, and sophisticated decor. Do NOT change the architecture (doors, windows, walls, ceiling, layout, or any fixed features), do NOT change light holder positions, and do NOT change the lighting coming from outside. Do NOT remove, hide, or alter any original paintings, wall art, or decorative items unless the user prompt or remove furniture option explicitly requests it. If the room is already furnished, do NOT change the full layout—just improve or enhance the existing furnishings and decor. Keep all original decor and artwork unless instructed otherwise. Add opulence and comfort.`,
};
