-- AlterTable
ALTER TABLE "photographer_profile"
ADD COLUMN IF NOT EXISTS "ratings" JSONB,
ADD COLUMN IF NOT EXISTS "reviews" JSONB,
ADD COLUMN IF NOT EXISTS "rating_average" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "rating_count" INTEGER NOT NULL DEFAULT 0;
